import Head from 'next/head'
import dynamic from 'next/dynamic'
import Image from 'next/image'
import { MDXProvider } from '@mdx-js/react'

import { Grid, Row } from 'layout'
import { Defaultpage } from 'templates/Defaultpage'

import styles from './Markdown.module.scss'

const RowParapraph = ({ children }) => (<Row><p className={styles.paragraph}>{children}</p></Row>)


const components = { 
  p: RowParapraph
}

export default function Markdown({ children, theme }) {

  return (
    <MDXProvider components={components}>

        {/* <Head>
          <title>Contact | Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head> */}
        <Grid>
          <h6>
            Markdown content from wrapper component
          </h6>
        </Grid>
        <Grid theme={theme} >
          {children}
        </Grid>


    </MDXProvider>
  )
}



