import { serialize } from 'next-mdx-remote/serialize'
import { MDXRemote } from 'next-mdx-remote'
import fs from 'fs'
// import path from 'path'
import Head from 'next/head'
import Link from 'next/link'

import { Grid } from 'layout'
import { Defaultpage } from 'templates/Defaultpage'
import styles from '../styles/Home.module.css'

const filePath = 'contents/about.mdx'

export default function Contact({ source }) {
  return (
    <Defaultpage theme="g10">
      <Head>
        <title>About | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid>
        <h1 className={styles.title}>
          Welcome to <Link href="/about">About Page!</Link>
        </h1>
      </Grid>
      <Grid>
        <MDXRemote {...source} />
      </Grid>

    </Defaultpage>
  )
}

export const getStaticProps = async () => {
  const source = fs.readFileSync(filePath)
  const mdxSource = await serialize(source)
  return {
    props: {
      source: mdxSource
    },
  }
}
