import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Image from 'next/image'
import ReactGA from "react-ga4"
import { Grid } from 'layout'
import { Defaultpage } from 'templates/Defaultpage'
import styles from 'styles/Home.module.css'

import Intro from 'components/Intro'

ReactGA.initialize('G-635CBZ242W');
ReactGA.send({ hitType: "pageview", page: "/portfolio", title: "Clicked portfolio (ie. from Resume)" });
ReactGA.send({ hitType: "pageview", page: "/#work", title: "Read section <Work>" });

export default function Home() {
  const router = useRouter();

  return (
    <Defaultpage hero theme="g90">
      <Head>
        <title>Home - I d I ™</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Intro />

      <button
        onClick={() => {
          router.push({
            pathname: "/",
            hash: "work"
          });
        }}
      >
        Static page with hash (good)
      </button>


      <Grid>
        <h1 className={styles.title}>
          Welcome, Welcome!
        </h1>
        <h2>Everybody is welcome!</h2>
      </Grid>




      <Grid>
        <div id="work" className={styles.grid}>
          <Link href="/work">
            <a className={styles.card}>
              <h2>See what i&#39;m doing &rarr;</h2>
              <p>Find in-depth information about my work.</p>
            </a>
          </Link>

          <Link href="/about">
            <a className={styles.card}>
              <h2>About me &rarr;</h2>
              <p>Learn more about me, get unique information!</p>
            </a>
          </Link>

          <Link href="/contact">
            <a className={styles.card}>
              <h2>Get in touch &rarr;</h2>
              <p>Professional in IT Industry, what to design something? So what are you waiting for?</p>
            </a>
          </Link>

          <Link href="/test">
            <a className={styles.card}>
              <h2>Test page &rarr;</h2>
              <p>This tets page with markdown dynamically loaded.</p>
            </a>
          </Link>
        </div>
      </Grid>
      
    </Defaultpage>
  )
}
