import React from 'react';
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
// import Image from 'next/image'


// Loader configuration needed for this
// https://webpack.js.org/concepts#loaders
// import Map from '../../../fibre/fibre-icons/src/icons/react/Map';

import { Grid, Row, Column } from 'layout'
import { BumperSection, Button, Callout, Card, CardGroup, ImageCard, Leadspace, Tile, ClickableTile, StaticTile } from 'components'
import { LogoGrid } from 'components/LogoGrid';
import { Homepage } from 'templates/Homepage'

import Hyphens from 'components/Brand/Hyphens';


import Intro from 'components/Intro'

import Section from 'containers/Section'



export default function Home() {
  const router = useRouter();

  return (
    <Homepage hero theme="g90">
      <Head>
        <title>Home - I d I ™</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Intro />

      
      



      <Callout 
        heading={`Designer × Developer`}
        paragraph={
          <>
              Creative <strong>Multi-disciplinary Graphic Designer</strong> with 15+ years{`’`} professional experience in print digital media. 
              Almost 10-years{`’`} professional approach and experience in information technology branch, interactive and advertising, 
              communication and marketing. Experienced in various roles in graphic design{`—`}team member and independent specialist, 
              participated and worked on many corporate projects, long-term B2B solutions and services located on all over the world.
          </>
        }
      >
        <Button
          kind="primary"
          renderIcon="ArrowDown"
          onClick={() => {
              router.push({
                pathname: "/",
                hash: "work"
              });
            }}
        >        
          Static page with hash (good)
        </Button>

        <Button kind="secondary" renderIcon />

        <Button renderIcon="ExternalLink">Click me!</Button> 

      </Callout>




      <Section id="work">
        <Row>
          <Column col={2} colSm={2} colMd={2} colLg={2}>
            <Hyphens.Work />
          </Column>
          <Column col={2} colSm={2} colMd={2} colLg={2}>
            <Hyphens.Work />
          </Column>
          <Column col={2} colSm={2} colMd={2} colLg={2}>
            <Hyphens.Work />
          </Column>
          <Column col={2} colSm={2} colMd={2} colLg={2}>
            <Hyphens.Work />
          </Column>
        </Row>
        <Row>
          <Column col={8} colSm={4} colMd={4} colLg={8}>
            <p className="ExpressiveParagraph">
            
                We welcome all feedback, designs, or ideas in order to produce the best possible experience for our users. 
                If you{`’`}re interested in contributing, check out our contributing guidelines to get started.
              
            </p> 
          </Column>
          {/* <Column col={4} colSm={4} colMd={4} colLg={4}>
            <Card
              title="See all work"
              href="/portfolio"
              subtitle={false}
              
              // col={4} colSm={2} colMd={4} colLg={4}
              ratio="2x1"
            >
              <p>Explore more work and all my portfolio and enjoy it!</p>
            </Card>
          </Column> */}
        </Row>

        
        
        <Row>
          <ImageCard col={4} colMd={8} colLg={4} image="https://images.unsplash.com/photo-1585298723682-7115561c51b7?q=80&w=3295&auto=format&fit=crop" ratio="1x1" dark />
          <ImageCard col={4} image="https://images.unsplash.com/photo-1497500002367-5eabaa373843?q=80&w=2944&auto=format&fit=crop" ratio="2x1" dark />
          <Column col={4} colMd={8} colLg={4} noGutter>
            <Card ratio="2x1" noGutter dark />
            <ImageCard ratio="1x1" image="https://images.unsplash.com/photo-1584457021185-49623a766992?q=80&w=2931&auto=format&fit=crop" />
          </Column>
        </Row>

        <Row>
          <Column col={4} colMd={4} colLg={4} noGutter>
            <BumperSection block="nearest" row={false} />
          </Column>
        </Row>

        <BumperSection block="nearest">
          <StaticTile col={4} colMd={8} colLg={4}>
          <p className="ExpressiveParagraph">
            
            We welcome all feedback, designs, or ideas in order to produce the best possible experience for our users. 
            If you{`’`}re interested in contributing, check out our contributing guidelines to get started.
          
          </p> 

          </StaticTile>

          <Column col={4} colSm={4} colMd={4} colLg={4}>
            <Card
              title="See all work"
              href="/portfolio"
              subtitle={false}
              
              // col={4} colSm={2} colMd={4} colLg={4}
              ratio="2x1"
            >
              <p>Explore more work and all my portfolio and enjoy it!</p>
            </Card>
          </Column>
        </BumperSection>
        <BumperSection block="nearest"/>
        <Row>
          <Column col={4} colMd={8} colLg={4} noGutter>
            <Card ratio="2x1" dark />
            <Card ratio="2x1" dark />
          </Column>
          
          <Card ratio="2x1" col={8} colMd={8} colLg={4} dark noGutter />

          <StaticTile col={4} colMd={8} colLg={4} ratio>
            <p className="ExpressiveParagraph-02" style={{ fontSize: '7.5vw' }}>Some Text here →</p> 
          </StaticTile>
          


          <Column col={4} colMd={4} colLg={4} noGutter>
            <Card ratio="1x1" dark />
            <Card ratio="2x1" dark />
          </Column>

          

          <Column col={4} colMd={4} colLg={4} noGutter>
            <Card ratio="1x2" dark />
          </Column>

          <Column col={4} colMd={8} colLg={4} noGutter>
            <Card ratio="2x1" dark />
            <Card ratio="1x1" dark />
          </Column>

          <Card ratio="4x3" col={8} colMd={8} colLg={8} noGutter dark/>
        </Row>
        
      </Section>




      <Grid theme="g20">
        <Row>
            <Card
              title="See what i&#39;m doing &rarr;"
              href="/work"
              subtitle={false}
              col={4} colSm={2} colMd={4} colLg={4}
              ratio="1x1"
              dark
            >
              <p>Find in-depth information about my work.</p>
            </Card>
            <Card
              title="About me &rarr;"
              href="/about"
              subtitle={false}
              col={4} colSm={2} colMd={4} colLg={4}
              ratio="2x1"
            >
              <p>Learn more about me, get unique information!</p>
            </Card>
            <Card
              title="Get in touch &rarr;"
              href="/contact"
              subtitle={false}
              col={4} colSm={2} colMd={4} colLg={4}
              ratio="2x1"
            >
              <p>Professional in IT Industry, what to design something? So what are you waiting for?</p>
            </Card>
            <Card
              title="Test page &rarr;"
              href="/test"
              subtitle={false}
              col={4} colSm={2} colMd={4} colLg={4}
              ratio="2x1"
            >
              <p>This tets page with markdown dynamically loaded.</p>
            </Card>
          </Row>


      </Grid>

      <Section id="about">
        <Row>
          <Column col={4} colSm={4} colMd={8} colLg={4}>
            <h3 className="ExpressiveHeading-02">Clients</h3>
            <p className="CapitalizedParagraph-01">
              Participated in corporate projects located on all over the world. Designed for brands like
            </p> 
          </Column>
          <Column col={8} colSm={4} colMd={8} colLg={8}>
            <LogoGrid />
          </Column>
        </Row>
      </Section>


      <Section id="contact">
        <Row>
          <Column col={4} colSm={4} colMd={4} colLg={6} noGutter>
            <StaticTile>
            <p className="CapitalizedParagraph-02">
            {<>
              We welcome all <em>feedback</em>, designs, or ideas in order to produce the best possible experience for our users. 
              If you{`’`}re interested in contributing, check out our contributing guidelines to get started.
            </>}
            </p> 
            </StaticTile>
          </Column>
          <Column col={4} colSm={4} colMd={4} colLg={6}>
            <Card
              title="Test page &rarr;"
              href="/test"
              subtitle={false}
              dark
              ratio="2x1"
            >
              <p>This test page with markdown dynamically loaded.</p>
            </Card>
          </Column>
        </Row>
      </Section>


    </Homepage>
  )
}




